server: 
  port: 7103

#kvdb:
#  type: 1
#  path: "/home/raft/leveldb-java1"
kvdb:
  type: 2
  path: "/home/raft/rocksdb-java3"

grpc:
  enable: true
  server:
    address: 127.0.0.1
    port: 1113
peer:
  groups:
    RAFT:
      - 127.0.0.1:1111:0:0
      - 127.0.0.1:1112:0:0
      - 127.0.0.1:1113:0:0
peers:
  enableKeepAlive: true
  keepAliveWithoutCalls: true
raft:
  dataDir: /home/raft/leveldbSTORE-java3
  heartbeatPeriodMilliseconds: 100
  electionTimeoutMilliseconds: 2000
spring:
  application:
    name: raft




